'use strict';
const fs=require('fs'), vm=require('vm'), path=require('path');
const root=path.resolve(__dirname,'..','phaser_map_beta');
const context={window:{}}; vm.createContext(context);
for(const f of ['entities-v0.js','combat-v0.js','enemy-ai-v0.js']) vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),context,{filename:f});
const E=context.window.RagbiaEntitiesV0, C=context.window.RagbiaCombatV0, AI=context.window.RagbiaEnemyAIV0;
const ents=E.createSlimes([{x:0,y:0},{x:100,y:100}]);
const p=ents[1];
if(p.id!=='slime-02'||p.behavior!=='passive'||p.maxHP!==2||p.hp!==2) throw new Error('SLIME-02 deve ser passivo HP 2/2');
let plan=AI.plan(p,110,100,true);
if(plan.mode!=='idle'||p.aggro) throw new Error('Passivo não pode adquirir por FOV');
const hit=C.applyDamage(p,1);
if(!hit.applied||hit.killed||p.hp!==1) throw new Error('Primeiro hit deve deixar passivo vivo em 1/2');
AI.provoke(p,'damage');
plan=AI.plan(p,600,100,true);
if(!p.aggro||plan.mode!=='chase') throw new Error('Passivo provocado deve perseguir como agressivo fora do FOV');
p.x=p.spawnX+705; p.y=p.spawnY;
plan=AI.plan(p,900,100,true);
if(plan.mode!=='reset'||p.damageable!==false||p.targetable!==false||p.hp!==2) throw new Error('Leash deve resetar e restaurar HP 2/2');
AI.finishReset(p);
plan=AI.plan(p,110,100,true);
if(p.behavior!=='passive'||p.aggro||plan.mode!=='idle'||p.hp!==2) throw new Error('Após reset deve voltar a passivo IDLE 2/2');
console.log('OK — M001.10 passivo reativo: dano -> aggro -> chase -> reset -> passivo.');
